# ******* DEFAULT *******
logging:
  level:
    arbetsformedlingen: INFO


loader:
  io:
    token: loaderio-2dbccb6f10b8be6dcf742bff1ecab72a

api:
  error:
    include-stacktrace: true
---

# ******* DEV *******
spring:
  profiles: dev
---

# ******* STAGE *******
spring:
  profiles: stage
---

# ******* PRODUCTION *******
spring:
  profiles: prod

logging:
  level:
    arbetsformedlingen: INFO

api:
  error:
    include-stacktrace: false
---
