# ******* DEFAULT *******
logging:
  level:
    arbetsformedlingen: DEBUG

loader:
  io:
    token: loaderio-2dbccb6f10b8be6dcf742bff1ecab72a

api:
  error:
    include-stacktrace: true

miljo: default-miljo
---

# ******* DEV *******
spring:
  profiles: dev

miljo: development-miljo
---

# ******* STAGE *******
spring:
  profiles: stage

miljo: stage-miljo
---

# ******* PRODUCTION *******
spring:
  profiles: prod

logging:
  level:
    arbetsformedlingen: INFO

api:
  error:
    include-stacktrace: false

miljo: production-miljo
---
